/** 扩展内部消息类型 */

export const MSG = {
  RUN_ALL: 'RUN_ALL',
  RUN_SITE: 'RUN_SITE',
  GET_STATUS: 'GET_STATUS',
  STATUS_UPDATE: 'STATUS_UPDATE',
  RESCHEDULE: 'RESCHEDULE',
  STOP: 'STOP',
  PING: 'PING',
  // Procedures
  PROCEDURE_LIST: 'PROCEDURE_LIST',
  PROCEDURE_SAVE: 'PROCEDURE_SAVE',
  PROCEDURE_DELETE: 'PROCEDURE_DELETE',
  // Market
  MARKET_INDEX: 'MARKET_INDEX',
  MARKET_INSTALL: 'MARKET_INSTALL',
};

export const RUN_STATE = {
  IDLE: 'idle',
  RUNNING: 'running',
  WAITING_CF: 'waiting_cf',
  NEED_MANUAL: 'need_manual',
};
